-- tools/bake_spleen.lua — bake spleen BDF fonts into committed engine font
-- modules (D010/D011: baked artifacts are committed so users never need the
-- font package or a build step). Run from the repo root inside the devshell:
--
--   nix develop -c lua tools/bake_spleen.lua
--
-- Output: engine/cm/assets/font_<gw>x<gh>.lua — a grid atlas of ASCII
-- 32..126 as a 1bpp hex string (row-major, MSB-first), decoded to an RGBA
-- texture at runtime by cm.text.

local dir = os.getenv("COSMIC_SPLEEN_DIR")
assert(dir, "COSMIC_SPLEEN_DIR not set; run inside nix develop")

local LICENSE = [[Spleen 2.1.0 — Copyright (c) 2018-2024, Frederic Cambus
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

  * Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.

  * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.]]

local FIRST, LAST = 32, 126
local COLS = 16

local function parse_bdf(path, gw, gh)
  local f = assert(io.open(path, "r"), "can't open " .. path)
  local glyphs = {} -- encoding -> array of row byte-arrays
  local enc, rows, inbitmap
  for line in f:lines() do
    if line:find("^ENCODING ") then
      enc = tonumber(line:match("^ENCODING (%-?%d+)"))
    elseif line:find("^BBX ") then
      local w, h, ox, oy = line:match("^BBX (%-?%d+) (%-?%d+) (%-?%d+) (%-?%d+)")
      if enc and enc >= FIRST and enc <= LAST then
        assert(tonumber(w) == gw and tonumber(h) == gh,
               "non-cell glyph at encoding " .. enc .. " (BBX " .. w .. "x" .. h
               .. ") — this tool only handles character-cell fonts")
        assert(tonumber(ox) == 0, "unexpected x offset at " .. enc)
        local _ = oy -- uniform per font; rows map 1:1 onto the cell
      end
    elseif line == "BITMAP" then
      inbitmap = true
      rows = {}
    elseif line == "ENDCHAR" then
      if inbitmap and enc and enc >= FIRST and enc <= LAST then
        assert(#rows == gh, "row count at encoding " .. enc)
        glyphs[enc] = rows
      end
      inbitmap, enc, rows = false, nil, nil
    elseif inbitmap then
      local bytes = {}
      for hexbyte in line:gmatch("%x%x") do
        bytes[#bytes + 1] = tonumber(hexbyte, 16)
      end
      rows[#rows + 1] = bytes
    end
  end
  f:close()
  for e = FIRST, LAST do
    assert(glyphs[e], "missing glyph for encoding " .. e)
  end
  return glyphs
end

local function bake(bdf, gw, gh)
  local glyphs = parse_bdf(dir .. "/" .. bdf, gw, gh)
  local count = LAST - FIRST + 1
  local grid_rows = math.ceil(count / COLS)
  local W, H = COLS * gw, grid_rows * gh
  assert(W % 8 == 0, "atlas width must be byte-aligned")

  local bytes = {}
  for i = 1, W * H // 8 do bytes[i] = 0 end
  for e = FIRST, LAST do
    local idx = e - FIRST
    local cx, cy = (idx % COLS) * gw, (idx // COLS) * gh
    for y = 1, gh do
      local row = glyphs[e][y]
      for x = 0, gw - 1 do
        local bit = (row[1 + x // 8] >> (7 - x % 8)) & 1
        if bit == 1 then
          local p = (cy + y - 1) * W + cx + x
          local bi = 1 + p // 8
          bytes[bi] = bytes[bi] | (1 << (7 - p % 8))
        end
      end
    end
  end

  local hex = {}
  for i, b in ipairs(bytes) do hex[i] = string.format("%02x", b) end
  local hexstr = table.concat(hex)
  local wrapped = {}
  for i = 1, #hexstr, 76 do wrapped[#wrapped + 1] = hexstr:sub(i, i + 75) end

  local out = ("engine/cm/assets/font_%dx%d.lua"):format(gw, gh)
  local f = assert(io.open(out, "w"))
  f:write(("-- generated by tools/bake_spleen.lua from %s — do not edit\n")
          :format(bdf))
  f:write("-- 1bpp grid atlas, row-major, MSB-first; decoded by cm.text\n")
  f:write("return {\n")
  f:write(("  gw = %d, gh = %d, cols = %d, first = %d, count = %d,\n")
          :format(gw, gh, COLS, FIRST, count))
  f:write(("  w = %d, h = %d,\n"):format(W, H))
  f:write('  bits = "' .. table.concat(wrapped, '"\n    .. "') .. '",\n')
  f:write("  license = [[\n" .. LICENSE .. "]],\n}\n")
  f:close()
  print(("baked %s -> %s (%dx%d atlas)"):format(bdf, out, W, H))
end

bake("spleen-5x8.bdf", 5, 8)
bake("spleen-8x16.bdf", 8, 16)
